In [69]:
import pandas as pd

In [70]:
matches_df = pd.read_csv("cleaned_data(week1).csv")
matches_df

,home_team,away_team,home_score,away_score,Round,Date,Score,Host,Year,winner,result_numeric
0,Argentina,France,3,3,Final,2022-12-18,(4) 3–3 (2),Qatar,2022,Draw,0
1,Croatia,Morocco,2,1,Third-place match,2022-12-17,2–1,Qatar,2022,Croatia,1
2,France,Morocco,2,0,Semi-finals,2022-12-14,2–0,Qatar,2022,France,1
3,Argentina,Croatia,3,0,Semi-finals,2022-12-13,3–0,Qatar,2022,Argentina,1
4,Morocco,Portugal,1,0,Quarter-finals,2022-12-10,1–0,Qatar,2022,Morocco,1
...,...,...,...,...,...,...,...,...,...,...,...
515,Argentina,Mexico,6,3,Group stage,1930-07-19,6–3,Uruguay,1930,Argentina,1
516,Uruguay,Peru,1,0,Group stage,1930-07-18,1–0,Uruguay,1930,Uruguay,1
517,Argentina,France,1,0,Group stage,1930-07-15,1–0,Uruguay,1930,Argentina,1
518,Romania,Peru,3,1,Group stage,1930-07-14,3–1,Uruguay,1930,Romania,1
519,France,Mexico,4,1,Group stage,1930-07-13,4–1,Uruguay,1930,France,1

In [71]:
rating_df=pd.read_csv('raw data/fifa_mens_rank.csv')
rating_df

,date,semester,rank,team,acronym,total.points,previous.points,diff.points
0,2024,2,1,Argentina,ARG,1867.25,1883.50,-16.25
1,2024,2,2,France,FRA,1859.78,1859.85,-0.07
2,2024,2,3,Spain,ESP,1853.27,1844.33,8.94
3,2024,2,4,England,ENG,1813.81,1807.83,5.98
4,2024,2,5,Brazil,BRA,1775.85,1784.37,-8.52
...,...,...,...,...,...,...,...,...
13125,1992,2,149,Lebanon,LBN,0.00,0.00,0.00
13126,1992,2,149,Bahamas,BAH,0.00,0.00,0.00
13127,1992,2,149,Maldives,MDV,0.00,0.00,0.00
13128,1992,2,149,Rwanda,RWA,0.00,0.00,0.00
13129,1992,2,149,Somalia,SOM,0.00,0.00,0.00

In [72]:
rating_df=rating_df[rating_df['date'] == 2024]
rating_df=rating_df[rating_df['semester'] == 2]
rating_df.drop([
    'semester',
    'acronym'
], axis=1, inplace=True)

In [73]:
rating_df = rating_df[rating_df['rank'] <= 48]
rating_df

    date  rank            team  total.points  previous.points  diff.points
0   2024     1       Argentina       1867.25          1883.50       -16.25
1   2024     2          France       1859.78          1859.85        -0.07
2   2024     3           Spain       1853.27          1844.33         8.94
3   2024     4         England       1813.81          1807.83         5.98
4   2024     5          Brazil       1775.85          1784.37        -8.52
5   2024     6        Portugal       1756.12          1752.68         3.44
6   2024     7     Netherlands       1747.55          1748.24        -0.69
7   2024     8         Belgium       1740.62          1761.27       -20.65
8   2024     9           Italy       1731.51          1729.40         2.11
9   2024    10         Germany       1703.79          1703.59         0.20
10  2024    11         Uruguay       1695.91          1680.36        15.55
11  2024    12        Colombia       1694.44          1724.37       -29.93
12  2024    13         Croatia       1691.59          1701.36        -9.77
13  2024    14         Morocco       1688.18          1681.57         6.61
14  2024    15           Japan       1652.79          1645.09         7.70
15  2024    16             USA       1645.48          1630.97        14.51
16  2024    17         Senegal       1637.25          1627.13        10.12
17  2024    18         IR Iran       1635.31          1627.58         7.73
18  2024    19          Mexico       1627.40          1640.67       -13.27
19  2024    20     Switzerland       1625.16          1631.38        -6.22
20  2024    21         Denmark       1611.49          1617.34        -5.85
21  2024    22         Austria       1589.84          1589.17         0.67
22  2024    23  Korea Republic       1585.45          1589.93        -4.48
23  2024    24         Ecuador       1560.13          1536.32        23.81
24  2024    25         Ukraine       1554.94          1552.37         2.57
25  2024    26       Australia       1544.15          1552.77        -8.62
26  2024    27          Sweden       1540.20          1530.41         9.79
27  2024    28         Türkiye       1537.24          1548.15       -10.91
28  2024    29           Wales       1534.39          1528.96         5.43
29  2024    30         Hungary       1517.57          1519.33        -1.76
30  2024    31          Canada       1515.96          1507.27         8.69
31  2024    32          Serbia       1514.28          1511.16         3.12
32  2024    33           Egypt       1513.48          1526.25       -12.77
33  2024    34          Russia       1512.32          1508.73         3.59
34  2024    35          Poland       1510.62          1523.19       -12.57
35  2024    36          Panama       1504.39          1493.80        10.59
36  2024    37         Algeria       1495.85          1496.94        -1.09
37  2024    38         Romania       1494.20          1487.22         6.98
38  2024    39          Greece       1489.88          1487.42         2.46
39  2024    40            Peru       1488.42          1494.24        -5.82
40  2024    41        Slovakia       1486.19          1489.88        -3.69
41  2024    42         Czechia       1484.88          1480.39         4.49
42  2024    43          Norway       1484.44          1473.50        10.94
43  2024    44         Nigeria       1482.23          1503.29       -21.06
44  2024    45        Scotland       1480.24          1461.34        18.90
45  2024    46   Côte d'Ivoire       1478.47          1493.57       -15.10
46  2024    47       Venezuela       1475.71          1482.47        -6.76
47  2024    48           Qatar       1474.60          1478.60        -4.00

In [74]:
matches_df

,home_team,away_team,home_score,away_score,Round,Date,Score,Host,Year,winner,result_numeric
0,Argentina,France,3,3,Final,2022-12-18,(4) 3–3 (2),Qatar,2022,Draw,0
1,Croatia,Morocco,2,1,Third-place match,2022-12-17,2–1,Qatar,2022,Croatia,1
2,France,Morocco,2,0,Semi-finals,2022-12-14,2–0,Qatar,2022,France,1
3,Argentina,Croatia,3,0,Semi-finals,2022-12-13,3–0,Qatar,2022,Argentina,1
4,Morocco,Portugal,1,0,Quarter-finals,2022-12-10,1–0,Qatar,2022,Morocco,1
...,...,...,...,...,...,...,...,...,...,...,...
515,Argentina,Mexico,6,3,Group stage,1930-07-19,6–3,Uruguay,1930,Argentina,1
516,Uruguay,Peru,1,0,Group stage,1930-07-18,1–0,Uruguay,1930,Uruguay,1
517,Argentina,France,1,0,Group stage,1930-07-15,1–0,Uruguay,1930,Argentina,1
518,Romania,Peru,3,1,Group stage,1930-07-14,3–1,Uruguay,1930,Romania,1
519,France,Mexico,4,1,Group stage,1930-07-13,4–1,Uruguay,1930,France,1

In [75]:
matches_df.drop('Year',axis=1)

,home_team,away_team,home_score,away_score,Round,Date,Score,Host,winner,result_numeric
0,Argentina,France,3,3,Final,2022-12-18,(4) 3–3 (2),Qatar,Draw,0
1,Croatia,Morocco,2,1,Third-place match,2022-12-17,2–1,Qatar,Croatia,1
2,France,Morocco,2,0,Semi-finals,2022-12-14,2–0,Qatar,France,1
3,Argentina,Croatia,3,0,Semi-finals,2022-12-13,3–0,Qatar,Argentina,1
4,Morocco,Portugal,1,0,Quarter-finals,2022-12-10,1–0,Qatar,Morocco,1
...,...,...,...,...,...,...,...,...,...,...
515,Argentina,Mexico,6,3,Group stage,1930-07-19,6–3,Uruguay,Argentina,1
516,Uruguay,Peru,1,0,Group stage,1930-07-18,1–0,Uruguay,Uruguay,1
517,Argentina,France,1,0,Group stage,1930-07-15,1–0,Uruguay,Argentina,1
518,Romania,Peru,3,1,Group stage,1930-07-14,3–1,Uruguay,Romania,1
519,France,Mexico,4,1,Group stage,1930-07-13,4–1,Uruguay,France,1

In [76]:
# First, keep only team and rank from rating_df
rating_rank = rating_df[['team', 'rank']]

# Add home_rank
matches_df = matches_df.merge(rating_rank, left_on='home_team', right_on='team')
matches_df = matches_df.rename(columns={'rank': 'home_rank'})
matches_df = matches_df.drop(columns=['team'])

# Add away_rank
matches_df = matches_df.merge(rating_rank, left_on='away_team', right_on='team')
matches_df = matches_df.rename(columns={'rank': 'away_rank'})
matches_df = matches_df.drop(columns=['team'])

# Create rank difference column
matches_df['rank_diff'] = matches_df['home_rank'] - matches_df['away_rank']

In [77]:
matches_df

,home_team,away_team,home_score,away_score,Round,Date,Score,Host,Year,winner,result_numeric,home_rank,away_rank,rank_diff
0,Argentina,France,3,3,Final,2022-12-18,(4) 3–3 (2),Qatar,2022,Draw,0,1,2,-1
1,Croatia,Morocco,2,1,Third-place match,2022-12-17,2–1,Qatar,2022,Croatia,1,13,14,-1
2,France,Morocco,2,0,Semi-finals,2022-12-14,2–0,Qatar,2022,France,1,2,14,-12
3,Argentina,Croatia,3,0,Semi-finals,2022-12-13,3–0,Qatar,2022,Argentina,1,1,13,-12
4,Morocco,Portugal,1,0,Quarter-finals,2022-12-10,1–0,Qatar,2022,Morocco,1,14,6,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,Argentina,Mexico,6,3,Group stage,1930-07-19,6–3,Uruguay,1930,Argentina,1,1,19,-18
516,Uruguay,Peru,1,0,Group stage,1930-07-18,1–0,Uruguay,1930,Uruguay,1,11,40,-29
517,Argentina,France,1,0,Group stage,1930-07-15,1–0,Uruguay,1930,Argentina,1,1,2,-1
518,Romania,Peru,3,1,Group stage,1930-07-14,3–1,Uruguay,1930,Romania,1,38,40,-2
519,France,Mexico,4,1,Group stage,1930-07-13,4–1,Uruguay,1930,France,1,2,19,-17

In [78]:
matches_df = matches_df[matches_df['Year'] > 2000].reset_index(drop=True)

In [79]:
# Rename for clarity
rating_df = rating_df.rename(columns={'team': 'Team', 'total.points': 'elo_rating'})

# Add home elo
matches_df = matches_df.merge(rating_df[['Team', 'elo_rating']], left_on='home_team', right_on='Team')
matches_df = matches_df.rename(columns={'elo_rating': 'home_elo'})
matches_df = matches_df.drop(columns=['Team'])

# Add away elo
matches_df = matches_df.merge(rating_df[['Team', 'elo_rating']], left_on='away_team', right_on='Team')
matches_df = matches_df.rename(columns={'elo_rating': 'away_elo'})
matches_df = matches_df.drop(columns=['Team'])

# Elo difference feature
matches_df['elo_diff'] = matches_df['home_elo'] - matches_df['away_elo']

matches_df

In [80]:
matches_df

,home_team,away_team,home_score,away_score,Round,Date,Score,Host,Year,winner,result_numeric,home_rank,away_rank,rank_diff,home_elo,away_elo,elo_diff
0,Argentina,France,3,3,Final,2022-12-18,(4) 3–3 (2),Qatar,2022,Draw,0,1,2,-1,1867.25,1859.78,7.47
1,Croatia,Morocco,2,1,Third-place match,2022-12-17,2–1,Qatar,2022,Croatia,1,13,14,-1,1691.59,1688.18,3.41
2,France,Morocco,2,0,Semi-finals,2022-12-14,2–0,Qatar,2022,France,1,2,14,-12,1859.78,1688.18,171.60
3,Argentina,Croatia,3,0,Semi-finals,2022-12-13,3–0,Qatar,2022,Argentina,1,1,13,-12,1867.25,1691.59,175.66
4,Morocco,Portugal,1,0,Quarter-finals,2022-12-10,1–0,Qatar,2022,Morocco,1,14,6,8,1688.18,1756.12,-67.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,Italy,Ecuador,2,0,Group stage,2002-06-03,2–0,"Korea Republic, Japan",2002,Italy,1,9,24,-15,1731.51,1560.13,171.38
237,Argentina,Nigeria,1,0,Group stage,2002-06-02,1–0,"Korea Republic, Japan",2002,Argentina,1,1,44,-43,1867.25,1482.23,385.02
238,England,Sweden,1,1,Group stage,2002-06-02,1–1,"Korea Republic, Japan",2002,Draw,0,4,27,-23,1813.81,1540.20,273.61
239,Uruguay,Denmark,1,2,Group stage,2002-06-01,1–2,"Korea Republic, Japan",2002,Denmark,-1,11,21,-10,1695.91,1611.49,84.42
240,France,Senegal,0,1,Group stage,2002-05-31,0–1,"Korea Republic, Japan",2002,Senegal,-1,2,17,-15,1859.78,1637.25,222.53

In [84]:
matches_df.drop([
    'Round',            
    'Date',
    'Host',
    'Year',
    'winner',
    'Score'
],axis=1)

,home_team,away_team,home_score,away_score,result_numeric,home_rank,away_rank,rank_diff,home_elo,away_elo,elo_diff
0,Argentina,France,3,3,0,1,2,-1,1867.25,1859.78,7.47
1,Croatia,Morocco,2,1,1,13,14,-1,1691.59,1688.18,3.41
2,France,Morocco,2,0,1,2,14,-12,1859.78,1688.18,171.60
3,Argentina,Croatia,3,0,1,1,13,-12,1867.25,1691.59,175.66
4,Morocco,Portugal,1,0,1,14,6,8,1688.18,1756.12,-67.94
...,...,...,...,...,...,...,...,...,...,...,...
236,Italy,Ecuador,2,0,1,9,24,-15,1731.51,1560.13,171.38
237,Argentina,Nigeria,1,0,1,1,44,-43,1867.25,1482.23,385.02
238,England,Sweden,1,1,0,4,27,-23,1813.81,1540.20,273.61
239,Uruguay,Denmark,1,2,-1,11,21,-10,1695.91,1611.49,84.42
240,France,Senegal,0,1,-1,2,17,-15,1859.78,1637.25,222.53

,home_team,away_team,home_score,away_score,Round,Date,Score,Host,Year,winner,result_numeric,home_rank,away_rank,rank_diff,home_elo,away_elo,elo_diff
0,Argentina,France,3,3,Final,2022-12-18,(4) 3–3 (2),Qatar,2022,Draw,0,1,2,-1,1867.25,1859.78,7.47
1,Croatia,Morocco,2,1,Third-place match,2022-12-17,2–1,Qatar,2022,Croatia,1,13,14,-1,1691.59,1688.18,3.41
2,France,Morocco,2,0,Semi-finals,2022-12-14,2–0,Qatar,2022,France,1,2,14,-12,1859.78,1688.18,171.60
3,Argentina,Croatia,3,0,Semi-finals,2022-12-13,3–0,Qatar,2022,Argentina,1,1,13,-12,1867.25,1691.59,175.66
4,Morocco,Portugal,1,0,Quarter-finals,2022-12-10,1–0,Qatar,2022,Morocco,1,14,6,8,1688.18,1756.12,-67.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,Italy,Ecuador,2,0,Group stage,2002-06-03,2–0,"Korea Republic, Japan",2002,Italy,1,9,24,-15,1731.51,1560.13,171.38
237,Argentina,Nigeria,1,0,Group stage,2002-06-02,1–0,"Korea Republic, Japan",2002,Argentina,1,1,44,-43,1867.25,1482.23,385.02
238,England,Sweden,1,1,Group stage,2002-06-02,1–1,"Korea Republic, Japan",2002,Draw,0,4,27,-23,1813.81,1540.20,273.61
239,Uruguay,Denmark,1,2,Group stage,2002-06-01,1–2,"Korea Republic, Japan",2002,Denmark,-1,11,21,-10,1695.91,1611.49,84.42
240,France,Senegal,0,1,Group stage,2002-05-31,0–1,"Korea Republic, Japan",2002,Senegal,-1,2,17,-15,1859.78,1637.25,222.53

In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm

# Load your current dataset
df = pd.read_csv('features.csv')

# Rename home/away to team1/team2
rename_map = {
    'home_team': 'team1',
    'away_team': 'team2',
    'home_score': 'team1_score',
    'away_score': 'team2_score',
    'home_elo': 'team1_elo',
    'away_elo': 'team2_elo',
    'home_rank': 'team1_rank',
    'away_rank': 'team2_rank'
}
df = df.rename(columns={k:v for k,v in rename_map.items() if k in df.columns})

# Sanity: drop any irrelevant columns
drop_cols = ['Round', 'Date', 'Score', 'Year', 'winner', 'Host']
df = df.drop(columns=[c for c in drop_cols if c in df.columns], errors='ignore')


df.head()

,team1,team2,team1_score,team2_score,result_numeric,team1_rank,team2_rank,rank_diff,team1_elo,team2_elo,elo_diff
0,Argentina,France,3,3,0,1,2,-1,1867.25,1859.78,7.47
1,Croatia,Morocco,2,1,1,13,14,-1,1691.59,1688.18,3.41
2,France,Morocco,2,0,1,2,14,-12,1859.78,1688.18,171.60
3,Argentina,Croatia,3,0,1,1,13,-12,1867.25,1691.59,175.66
4,Morocco,Portugal,1,0,1,14,6,8,1688.18,1756.12,-67.94

In [3]:
df.to_csv('features_O.csv',index=False)

In [6]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv("features.csv")

# Initialize each team's starting Elo using the existing ratings
current_elo = {}
teams = pd.unique(df[['team1', 'team2']].values.ravel())

for t in teams:
    first_team1 = df.loc[df['team1'] == t, 'team1_elo']
    first_team2 = df.loc[df['team2'] == t, 'team2_elo']
    if not first_team1.empty:
        current_elo[t] = float(first_team1.iloc[0])
    elif not first_team2.empty:
        current_elo[t] = float(first_team2.iloc[0])
    else:
        current_elo[t] = 1500.0  # fallback (very rare)

# Elo constants
K = 40.0  # sensitivity factor

records = []

# Compute match-by-match features
for _, row in df.iterrows():
    t1, t2 = row['team1'], row['team2']
    s1, s2 = row['team1_score'], row['team2_score']

    # Current Elo ratings
    E1 = current_elo.get(t1, 1500.0)
    E2 = current_elo.get(t2, 1500.0)

    # Expected probability (no home advantage)
    exp1 = 1 / (1 + 10 ** ((E2 - E1) / 400))
    exp2 = 1 - exp1

    # Actual results
    if s1 > s2:
        S1, S2 = 1, 0
    elif s1 < s2:
        S1, S2 = 0, 1
    else:
        S1, S2 = 0.5, 0.5

    # Goal margin multiplier
    goal_diff = abs(int(s1) - int(s2))
    G = np.log(goal_diff + 1) * 0.5

    # Elo updates
    E1_new = E1 + K * G * (S1 - exp1)
    E2_new = E2 + K * G * (S2 - exp2)

    # Store results
    records.append({
        "team1": t1,
        "team2": t2,
        "team1_elo_before": E1,
        "team2_elo_before": E2,
        "elo_diff_before": E1 - E2,
        "expected_team1_win": exp1,
        "goal_margin_factor": G,
        "team1_elo_after": E1_new,
        "team2_elo_after": E2_new,
        "elo_change_team1": E1_new - E1,
        "elo_change_team2": E2_new - E2,
        "result_numeric": row.get("result_numeric", np.nan)
    })

    # Update Elo ratings for next iteration
    current_elo[t1] = E1_new
    current_elo[t2] = E2_new

# Build the new DataFrame
elo_features = pd.DataFrame(records)

# Display first few rows
print(elo_features.head())

# Save to CSV
elo_features.to_csv("elo_features_O.csv", index=False)

       team1     team2  team1_elo_before  team2_elo_before  elo_diff_before  \
0  Argentina    France       1867.250000       1859.780000         7.470000
1    Croatia   Morocco       1691.590000       1688.180000         3.410000
2     France   Morocco       1859.780000       1681.316557       178.463443
3  Argentina   Croatia       1867.250000       1698.453443       168.796557
4    Morocco  Portugal       1675.524577       1756.120000       -80.595423

   expected_team1_win  goal_margin_factor  team1_elo_after  team2_elo_after  \
0            0.510749            0.000000      1867.250000      1859.780000
1            0.504907            0.346574      1698.453443      1681.316557
2            0.736396            0.549306      1865.571980      1675.524577
3            0.725452            0.693147      1874.862074      1690.841369
4            0.386050            0.346574      1684.035724      1747.608852

   elo_change_team1  elo_change_team2  result_numeric
0          0.000000          0.000000               0
1          6.863443         -6.863443               1
2          5.791980         -5.791980               1
3          7.612074         -7.612074               1
4          8.511148         -8.511148               1

In [8]:
elo_features

,team1,team2,team1_elo_before,team2_elo_before,elo_diff_before,expected_team1_win,goal_margin_factor,team1_elo_after,team2_elo_after,elo_change_team1,elo_change_team2,result_numeric
0,Argentina,France,1867.250000,1859.780000,7.470000,0.510749,0.000000,1867.250000,1859.780000,0.000000,0.000000,0
1,Croatia,Morocco,1691.590000,1688.180000,3.410000,0.504907,0.346574,1698.453443,1681.316557,6.863443,-6.863443,1
2,France,Morocco,1859.780000,1681.316557,178.463443,0.736396,0.549306,1865.571980,1675.524577,5.791980,-5.791980,1
3,Argentina,Croatia,1867.250000,1698.453443,168.796557,0.725452,0.693147,1874.862074,1690.841369,7.612074,-7.612074,1
4,Morocco,Portugal,1675.524577,1756.120000,-80.595423,0.386050,0.346574,1684.035724,1747.608852,8.511148,-8.511148,1
...,...,...,...,...,...,...,...,...,...,...,...,...
236,Italy,Ecuador,1726.044795,1561.153301,164.891494,0.720953,0.549306,1732.176093,1555.022003,6.131298,-6.131298,1
237,Argentina,Nigeria,1848.100786,1460.116549,387.984237,0.903210,0.346574,1849.442573,1458.774761,1.341788,-1.341788,1
238,England,Sweden,1786.675813,1558.969953,227.705860,0.787644,0.000000,1786.675813,1558.969953,0.000000,0.000000,0
239,Uruguay,Denmark,1704.841804,1602.603637,102.238167,0.643028,0.346574,1695.927546,1611.517895,-8.914259,8.914259,-1
240,France,Senegal,1881.031252,1629.641163,251.390088,0.809554,0.346574,1869.808444,1640.863971,-11.222808,11.222808,-1